import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-screen flex justify-between">
        <h1 className="text-maincolor absolute top-[40px] left-[50%] -translate-x-1/2 text-[120px] z-50">
          casestudy
        </h1>
        <div className="textfield mx-[100px] mt-[40px] pt-[300px]">
          <div className="absolute top-[40px]">
            <Image src="/logoL.png" height={"40px"} width={"150px"} />
          </div>
          <div className="w-[400px] h-[100px] font-sans	">
            Bamboo is a furnitutre company that provide quality product to meet
            your indoor or outdoor furniture needs.
          </div>
          <div className="w-[400px] h-[100px] ">
            Bamboo e-commerce site is a solution that offer a simple system that
            organize different product where peoples(families, businesses) can
            intereact with the product.
          </div>
        </div>
        <div className="imgfield">
          <div>
            <Image src="/homepageimg1.png" height={"320px"} width={"600px"} />
          </div>
          <div>
            <Image src="/homepageimg2.png" height={"320px"} width={"600px"} />
          </div>
        </div>
      </div>
      <div className="bg-maincolor h-screen flex items-center relative">
        <div className="mr-[200px] ">
          <div className="flex absolute items-center gap-10 top-[35px] left-[200px]">
            <div>
              <Image src="/logoW.png" width={"110px"} height={"20px"} />
            </div>
            <div>
              <h1 className="text-[36px] font-[700] text-white ">Casestudy</h1>
            </div>
          </div>
          <div className="w-screen">
            <h1 className="text-[85px] font-[600] text-white ml-[425px]">
              goal
            </h1>
            <div className="grid grid-cols-2 ml-[120px] mt-[80px]">
              <div>
                <h5 className="text-textaqua font-[600] text-[24px]">
                  SALE SOLUTION
                </h5>
                <p className="h-[120px] w-[350px] text-white">
                  The Bamboo E-commerce site provide a digital space were
                  digital transaction can take place between the buyer and
                  seller.
                </p>
              </div>
              <div>
                <h5 className="text-textaqua font-[600] text-[24px]">
                  PRODUCT HUB
                </h5>
                <p className="h-[120px] w-[350px] text-white">
                  The Platform provide a single source of truth for all all
                  things furniture to interested parties and eventually be
                  converted to a Lead
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-white h-screen relative flex justify-between">
        <div className="flex">
          <div className="flex items-center gap-5 left-[150px] absolute  top-[35px] ">
            <div>
              <Image src="/logoB.png" width={"110px"} height={"20px"} />
            </div>
            <div>
              <h1 className="text-[35px] font-[500] text-maincolor ">
                Casestudy
              </h1>
            </div>
          </div>

          <div className="absolute  text-maincolor left-[100px] top-[250px] text-[36px] font-[700]">
            <p>MODERN/CLASSIC</p>
            <p>SIMPLE/GENIUNE</p>
            <p>EARTHLY</p>
          </div>
        </div>

        <div className="w-1/2 text-end">
          <h1 className="text-maincolor mt-[85px] text-[85px] font-[600]">
            traits
          </h1>
        </div>
        <div className="relative w-[450px] h-[650px] mt-[30px] mr-[50px]">
          <Image src="/GroupI.png" layout={"fill"} objectFit={"fit "} />
        </div>
      </div>
    </div>
  );
}
