import Head from 'next/head'
import Navbar from './components/Navbar'
import Footer_2 from './components/Footer_2'
import Product from './components/Product'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar/>
      <div className='detail-content h-screen'> 
      <Product image={"Product1.png"} />
      </div>
      <Footer_2/>
    </div>
  )
}
